---
- name: Setting java update true if required
  set_fact:
    javaUpdateState: latest
  when: updateJava

- name: Install Openjdk | {{ javaVersion }} | Ubuntu
  apt:
    name: "{{ item }}"
    state: "{{ javaUpdateState | default('present') }}"
    update_cache: true
  loop:
    - "openjdk-{{ javaVersion }}-jdk-headless"
