---

- name: Creating installing dir | {{ kafkaInstallDir }}
  file:
    path: "{{ kafkaInstallDir }}"
    state: directory
  check_mode: no

- name: Creating kafka directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    mode: 0775
  loop:
    - "{{ kafkaDataDir }}"
    - "{{ kafkaLogDir }}"
  check_mode: no
