---

- name: creating kafka group
  group:
    name: "{{  kafkaGroup }}"
    gid: "{{ kafkaGroupId }}"
    state: present
  check_mode: no

- name: creating kafka user
  user:
    name: "{{ kafkaUser }}"
    comment: kafka Default User
    uid: "{{ kafkaUserId }}"
    group: "{{ kafkaGroup }}"
    shell: "/usr/bin/bash"
  check_mode: no

- name: update shell
  user:
    name: "{{ kafkaUser }}"
    shell: "/usr/bin/bash"
